# Generated by Django 5.1.2 on 2024-10-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
