# Generated by Django 5.1.2 on 2024-10-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
